### ISSUE TITLE
Change behavior of nested `.only`?

### ISSUE THREAD

**Issue by BiterUnion** [GlassBricks/Testorio#1]
I was wondering if it would be possible to change the behavior of nested `.only` calls. Consider this setup:

```
describe.only('MyClass', function()
    it('does this', function()
        ...
    end)
    it.only('does that', function()
        ...
    end)
end)
```

This currently executes both tests, but I would expect it to only execute the second one.

Use-case: when adding tests for a new class, I usually start by adding a `describe` block for that class and setting it to only. I then add `it` blocks for the tests and might want to focus further on a single test. To achieve this I have to remove the `.only` from the `describe` block and add it to the `it` block I want to focus on. Having to add `.only` only to the `it` block would make this much more convenient.

**Comment by GlassBricks** [comment]
This seems like a good idea; some other test frameworks (like `jest`) also do this.
This will be implemented in the next version.

**Comment by GlassBricks** [comment]
This change has been implemented in v1.5.

**Comment by BiterUnion** [comment]
Thanks, this works for simple cases now!
However, it still ignores the inner `.only`, if there is deeper nesting involved, for example:

    describe.only('Level1', function()
        describe('Level2', function()
            it.only('Test1', function()
    
            end)
            it('Test2', function()
    
            end)
        end)
    end)

This still executes Tests 1 and 2. Would appreciate it, if you could fix these cases as well.

**Comment by GlassBricks** [comment]
Supporting arbitrary nesting gets complicated real quick.
Additionally, looking at `jest`'s source code, they also only support only 1 level of nesting.

So, I don't think it's worth implement this. The workaround for now is to manually update your `.only`s.
